### ISSUE TITLE
can not use on react-native 0.44

### ISSUE THREAD

**Issue by xy371661665** [maxs15/react-native-spinkit#68]

**Comment by AfflatusX** [comment]
Same here - 

`Error: ENOENT: no such file or directory, open '/Users/txie/Documents/GitHub/Recip/client/RecipRN/android/build.gradle'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.<anonymous> (/Users/txie/Documents/GitHub/Recip/client/RecipRN/node_modules/react-native-spinkit/scripts/rnpm-prelink.js:7:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
Failed to load `android/build.gradle` when linking react-native-spinkit
Could not find `allprojects { }` block in build.gradle
/Users/txie/Documents/GitHub/Recip/client/RecipRN/node_modules/react-native-spinkit/scripts/rnpm-prelink.js:21
var str = depStr[0];
                ^

TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/Users/txie/Documents/GitHub/Recip/client/RecipRN/node_modules/react-native-spinkit/scripts/rnpm-prelink.js:21:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
/Users/txie/Documents/GitHub/Recip/client/RecipRN/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node ./node_modules/react-native-spinkit/scripts/rnpm-prelink.js" command
    at ChildProcess.prelink (/Users/txie/Documents/GitHub/Recip/client/RecipRN/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)`

looks like it's trying to find the build.gradle from wrong path (or maybe for RN 0.44+ we no longer have that file?)

**Comment by NikiLee2016** [comment]
Me neither. my version is 0.46.

**Comment by nschurmann** [comment]
me neither!
